language: generic
script:
- mkdir out
- echo Deployed at $(date) > out/index.html
- echo Success!
deploy:
  provider: pages
  edge:
    source: jyasskin/dpl
    branch: github-deploy-token
  skip_cleanup: true
  on:
    branch: master
  local_dir: out
  deploy_key: "$DEPLOY_KEY"
env:
  global:
    secure: j7qD3bHD/tKdDnbyYBD3R0gIyFOWsvBMGz7xoS0aeWIRQH5Ns/pTGmcb20/XdkyuEVto927tqkDQD0jJ41gIjjruRFXstSFw08r0IwB8ypA3HTcTbQYZWQdgUbC3xL7B7Jfgft1/GzTThCSG6h64fQCETOOVHP0WjyPw+04dsAV7AqULvTsDtEuUGPeijCSsfalFc8gqpGFBvqo3eAtGtSSZWV56ZN4+6Kv8K1/jbyp6fvla6tCdvqAIRlJD/3RjWKppni+U8csspKkKMae1aMCNEy4e3yCc5e+gf2gURH9s1CT4PFX5q9SfQdtpgZAV+dek8RD/4Yp7uoLOX4Vwof8XEjLuSapDWfLG1MyoAkysdVTR3p114jiLFTicQd28fD9ywuaoDqwBCIUjL+pRNcFhC+ob6fXHrMa22r6Pkq0oqc22Wc0WnS3C2QXwuwBQebiD7/vs5M8gdvQah5Y/5GKeKvjYjGkTcQLP6Z18k0HA330O4GM11ObJzNtO+5LNG+jP0+NcxwoJCq9xT7UTKwOqmYRpibiBINzedKA7JYtlPBadF5obcKXGyU0ZY8bnU9cKZFmo3PdHDahU8EBYAi1T3Q1NuUt/gvv8UCAxVAf5k9YNoEnJOKizKsCo1CJZwUx/cm0fYpgVTp0THc9VjKwEl0hKk0FqXP+jdhzaNgs=
