language: generic
script:
- mkdir out
- echo "$DEPLOY_KEY"
- echo Deployed at $(date) > out/index.html
- echo Success!
deploy:
  provider: pages
  edge:
    source: jyasskin/dpl
    branch: github-deploy-token
  skip_cleanup: true
  on:
    branch: master
  local_dir: out
  deploy_key: "$DEPLOY_KEY"
env:
  global:
    secure: BeBw1QR/SibThrnABvx/JdGz3j/orKHFyGRgJv1ECzUVxSB8sFuPNbtGIuTQMYR30ao7tHzSun4H3vLksNhIqXCW+jAxiJuFuwwfRSIquvlmub0qKRK0D3M4xAvIlj6VXvH3LAGjQpzG/wwznn/s9iIZHQdTd/5NphOUqRZ1m0tnHvy0ZA06VSoR92Rv56D5opsXVcxVpOcWaIpC/FxHRBTlbzguiYQhi/HTL9RrVnSsFkrF1BJIZ+y+eFwht3UBT2PV0H3yA9+BJ//F/6vJaxBHXfAYJqzLDntog4QN36zJ9zS5wK8ZP/zl9sM2Eyhb0sJGp/h74bkQvYNy6uDm+9laE2tk8RVwKLw4A/RBRGGMd0GzS+G4N0j/xGMuW89GMQ48e+hZ9fSFpLxv6uo1IGEhzR1uUfu47Z+XfY297zgZHZG/qk98kFmAwq0COJsH9MVWUCl6+4TuXW5VTjsO5Vvb21HY3egqeawF9LCRvn7KfLSU3nE6CPzFetMr29CC9RIkWjkoQT0Ta9Q5SlaZMPWLE7nukekfmsgh1VLf5kJAbwqrfnuz8+iqkh/gNv23pgyuSKsotjVCBqQFrF/pT3WPQr4j8JxqmH5RSxG3bzA7Q4PJFK2cYcTHSMs9Lg2dTzloxqh3turljD24yt9LrbXTF8bSAslyz1lkmPDP/I8=
